name: Validate

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate-hacs:
    name: Validate HACS
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: HACS validation
        uses: hacs/action@22.5.0
        with:
          category: integration

  validate-hassfest:
    name: Validate with hassfest
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: hassfest validation
        uses: home-assistant/actions/hassfest@master
